
import mods.embers.Stamper;
import mods.embers.Mixer;
import mods.embers.Melter;

import mods.appliedenergistics2.Grinder;

val anyAluminumOre = <ore:oreAluminum>;
val anyAluminumIngot = <ore:ingotAluminum>;
val anyAluminumNugget = <ore:nuggetAluminum>;
val anyAluminumPlate = <ore:plateAluminum>;
val anyAluminumGear = <ore:gearAluminum>;
val anyAluminumBrassIngot = <ore:ingotAlubrass>;
val anyAluminumBrassNugget = <ore:nuggetAlubrass>;
val anyAlumiteIngot = <ore:ingotAlumite>;
val anyAlumiteNugget = <ore:nuggetAlumite>;
val anyBrassIngot = <ore:ingotBrass>;
val anyBrassNugget = <ore:nuggetBrass>;
val anyBrassPlate = <ore:plateBrass>;
val anyBronzeIngot = <ore:ingotBronze>;
val anyBronzeNugget = <ore:nuggetBronze>;
val anyBronzePlate = <ore:plateBronze>;
val anyBronzeGear = <ore:gearBronze>;
val anyConductiveIronIngot = <ore:ingotConductiveIron>;
val anyConductiveIronNugget = <ore:nuggetConductiveIron>;
val anyConstantanIngot = <ore:ingotConstantan>;
val anyConstantanNugget = <ore:nuggetConstantan>;
val anyConstantanPlate = <ore:plateConstantan>;
val anyConstantanGear = <ore:gearConstantan>;
val anyCopperOre = <ore:oreCopper>;
val anyCopperIngot = <ore:ingotCopper>;
val anyCopperPlate = <ore:plateCopper>;
val anyCopperGear = <ore:gearCopper>;
val anyDarkSteelIngot = <ore:ingotDarkSteel>;
val anyDarkSteelNugget = <ore:nuggetDarkSteel>;
val anyElectricalSteelIngot = <ore:ingotElectricalSteel>;
val anyElectricalSteelNugget = <ore:nuggetElectricalSteel>;
val anyElectrumIngot = <ore:ingotElectrum>;
val anyElectrumNugget = <ore:nuggetElectrum>;
val anyElectrumPlate = <ore:plateElectrum>;
val anyElectrumGear = <ore:gearElectrum>;
val anyElementiumIngot = <ore:ingotElvenElementium>;
val anyElementiumNugget = <ore:nuggetElvenElementium>;
val anyEndSteelIngot = <ore:ingotEndSteel>;
val anyEndSteelNugget = <ore:nuggetEndSteel>;
val anyEnderiumIngot = <ore:ingotEnderium>;
val anyEnderiumNugget = <ore:nuggetEnderium>;
val anyEnderiumPlate = <ore:plateEnderium>;
val anyEnderiumGear = <ore:gearEnderium>;
val anyEnergeticAlloyIngot = <ore:ingotEnergeticAlloy>;
val anyEnergeticAlloyNugget = <ore:nuggetEnergeticAlloy>;
val anyGoldIngot = <ore:ingotGold>;
val anyGoldPlate = <ore:plateGold>;
val anyGoldGear = <ore:gearGold>;
val anyInvarIngot = <ore:ingotInvar>;
val anyInvarNugget = <ore:nuggetInvar>;
val anyInvarPlate = <ore:plateInvar>;
val anyInvarGear = <ore:gearInvar>;
val anyIridiumPlate = <ore:plateIridium>;
val anyIridiumGear = <ore:gearIridium>;
val anyIronIngot = <ore:ingotIron>;
val anyIronPlate = <ore:plateIron>;
val anyIronGear = <ore:gearIron>;
val anyIronAlloyIngot = <ore:ingotConstructionAlloy>;
val anyIronAlloyNugget = <ore:nuggetConstructionAlloy>;
val anyLeadOre = <ore:oreLead>;
val anyLeadIngot = <ore:ingotLead>;
val anyLeadPlate = <ore:plateLead>;
val anyLeadGear = <ore:gearLead>;
val anyLumiumIngot = <ore:ingotLumium>;
val anyLumiumNugget = <ore:nuggetLumium>;
val anyLumiumPlate = <ore:plateLumium>;
val anyLumiumGear = <ore:gearLumium>;
val anyManasteelIngot = <ore:ingotManasteel>;
val anyManasteelNugget = <ore:nuggetManasteel>;
val anyManyullynIngot = <ore:ingotManyullyn>;
val anyManyullynNugget = <ore:nuggetManyullyn>;
val anyMirionIngot = <ore:ingotMirion>;
val anyMirionNugget = <ore:nuggetMirion>;
val anyNickelOre = <ore:oreNickel>;
val anyNickelIngot = <ore:ingotNickel>;
val anyNickelNugget = <ore:nuggetNickel>;
val anyNickelPlate = <ore:plateNickel>;
val anyNickelGear = <ore:gearNickel>;
val anyPlatinumPlate = <ore:platePlatinum>;
val anyPlatinumGear = <ore:gearPlatinum>;
val anyPsimetalIngot = <ore:ingotPsimetal>;
val anyPulsatingIronIngot = <ore:ingotPulsatingIron>;
val anyPulsatingIronNugget = <ore:nuggetPulsatingIron>;
val anyQuartzOre = <ore:oreQuartz>;
val anyRedstoneAlloyIngot = <ore:ingotRedstoneAlloy>;
val anyRedstoneAlloyNugget = <ore:nuggetRedstoneAlloy>;
val anySignalumIngot = <ore:ingotSignalum>;
val anySignalumNugget = <ore:nuggetSignalum>;
val anySignalumPlate = <ore:plateSignalum>;
val anySignalumGear = <ore:gearSignalum>;
val anySilverOre = <ore:oreSilver>;
val anySilverIngot = <ore:ingotSilver>;
val anySilverPlate = <ore:plateSilver>;
val anySilverGear = <ore:gearSilver>;
val anySoulariumIngot = <ore:ingotSoularium>;
val anySoulariumNugget = <ore:nuggetSoularium>;
val anySteelIngot = <ore:ingotSteel>;
val anySteelNugget = <ore:nuggetSteel>;
val anySteelPlate = <ore:plateSteel>;
val anySteelGear = <ore:gearSteel>;
val anyTerrasteelIngot = <ore:ingotTerrasteel>;
val anyTerrasteelNugget = <ore:nuggetTerrasteel>;
val anyThaumiumIngot = <ore:ingotThaumium>;
val anyThaumiumNugget = <ore:nuggetThaumium>;
val anyThaumiumPlate = <ore:plateThaumium>;
val anyTinOre = <ore:oreTin>;
val anyTinIngot = <ore:ingotTin>;
val anyTinNugget = <ore:nuggetTin>;
val anyTinPlate = <ore:plateTin>;
val anyTinGear = <ore:gearTin>;
val anyUraniumPlate = <ore:plateUranium>;
val anyVibrantAlloyIngot = <ore:ingotVibrantAlloy>;
val anyVibrantAlloyNugget = <ore:nuggetVibrantAlloy>;

val ironIngot = <minecraft:iron_ingot>;
val goldIngot = <minecraft:gold_ingot>;
val copperIngotTE = <thermalfoundation:material:128>;
val tinIngotTE = <thermalfoundation:material:129>;
val aluminumIngotTE = <thermalfoundation:material:132>;
val leadIngotTE = <thermalfoundation:material:131>;
val silverIngotTE = <thermalfoundation:material:130>;
val nickelIngotTE = <thermalfoundation:material:133>;
val steelIngotTE = <thermalfoundation:material:160>;
val bronzeIngotTE = <thermalfoundation:material:163>;
val electrumIngotTE = <thermalfoundation:material:161>;
val constantanIngotTE = <thermalfoundation:material:164>;
val aluminumBrassIngot = <tconstruct:ingots:5>;
val alumiteIngot = <plustic:alumiteingot>;
val alchemicalBrassIngot = <thaumcraft:ingot:2>;
val bronzeIngot = <thermalfoundation:material:163>;
val cobaltIngot = <tconstruct:ingots:0>;
val conductiveIronIngot = <enderio:item_alloy_ingot:4>;
val constantanIngot = <thermalfoundation:material:164>;
val darkSteelIngot = <enderio:item_alloy_ingot:6>;
val electricalSteelIngot = <enderio:item_alloy_ingot:0>;
val electrumIngot = <thermalfoundation:material:161>;
val endSteelIngot = <enderio:item_alloy_ingot:8>;
val enderiumIngot = <thermalfoundation:material:167>;
val energeticAlloyIngot = <enderio:item_alloy_ingot:1>;
val invarIngot = <thermalfoundation:material:162>;
val ironAlloyIngot = <enderio:item_alloy_ingot:9>;
val lumiumIngot = <thermalfoundation:material:166>;
val manasteelIngot = <botania:manaresource>;
val manyullynIngot = <tconstruct:ingots:2>;
val mirionIngot = <plustic:mirioningot>;
val nickelIngot = <thermalfoundation:material:133>;
val psimetalIngot = <psi:material:1>;
val pulsatingIronIngot = <enderio:item_alloy_ingot:5>;
val redstoneAlloyIngot = <enderio:item_alloy_ingot:3>;
val signalumIngot = <thermalfoundation:material:165>;
val soulariumIngot = <enderio:item_alloy_ingot:7>;
val steelIngot = <thermalfoundation:material:160>;
val terrasteelIngot = <botania:manaresource:4>;
val thaumiumIngot = <thaumcraft:ingot:0>;
val tinIngot = <thermalfoundation:material:129>;
val vibrantAlloyIngot = <enderio:item_alloy_ingot:2>;

val ironPlateTE = <thermalfoundation:material:32>;
val goldPlateTE = <thermalfoundation:material:33>;
val copperPlateTE = <thermalfoundation:material:320>;
val leadPlateTE = <thermalfoundation:material:323>;
val silverPlateTE = <thermalfoundation:material:322>;
val aluminumPlate = <thermalfoundation:material:324>;
val brassPlate = <thaumcraft:plate>;
val bronzePlate = <thermalfoundation:material:355>;
val constantanPlate = <thermalfoundation:material:356>;
val electrumPlate = <thermalfoundation:material:353>;
val enderiumPlate = <thermalfoundation:material:359>;
val invarPlate = <thermalfoundation:material:354>;
val iridiumPlate = <thermalfoundation:material:327>;
val lumiumPlate = <thermalfoundation:material:358>;
val nickelPlate = <thermalfoundation:material:325>;
val platinumPlate = <thermalfoundation:material:326>;
val signalumPlate = <thermalfoundation:material:357>;
val steelPlate = <thermalfoundation:material:352>;
val thaumiumPlate = <thaumcraft:plate:2>;
val tinPlate = <thermalfoundation:material:321>;

val aluminumGear = <thermalfoundation:material:260>;
val bronzeGear = <thermalfoundation:material:291>;
val constantanGear = <thermalfoundation:material:292>;
val copperGear = <thermalfoundation:material:256>;
val electrumGear = <thermalfoundation:material:289>;
val enderiumGear = <thermalfoundation:material:295>;
val goldGear = <thermalfoundation:material:25>;
val invarGear = <thermalfoundation:material:290>;
val iridiumGear = <thermalfoundation:material:263>;
val ironGear = <thermalfoundation:material:24>;
val leadGear = <thermalfoundation:material:259>;
val lumiumGear = <thermalfoundation:material:294>;
val nickelGear = <thermalfoundation:material:261>;
val platinumGear = <thermalfoundation:material:262>;
val signalumGear = <thermalfoundation:material:293>;
val silverGear = <thermalfoundation:material:258>;
val steelGear = <thermalfoundation:material:288>;
val tinGear = <thermalfoundation:material:257>;

val destabilizedRedstone = <fluid:redstone>;

val moltenAluminum = <fluid:aluminum>;
val moltenAluminumBrass = <fluid:alubrass>;
val moltenAlumite = <fluid:alumite>;
val moltenArdite = <fluid:ardite>;
val moltenBrass = <fluid:brass>;
val moltenBronze = <fluid:bronze>;
val moltenCobalt = <fluid:cobalt>;
val moltenConductiveIron = <fluid:conductive_iron>;
val moltenConstantan = <fluid:constantan>;
val moltenCopper = <fluid:copper>;
val moltenDarkSteel = <fluid:dark_steel>;
val moltenElectricalSteel = <fluid:electrical_steel>;
val moltenElectrum = <fluid:electrum>;
val moltenElementium = <fluid:elementium>;
val moltenEndSteel = <fluid:end_steel>;
val moltenEnderium = <fluid:enderium>;
val moltenEnergeticAlloy = <fluid:energetic_alloy>;
val moltenGold = <fluid:gold>;
val moltenInvar = <fluid:invar>;
val moltenIridium = <fluid:iridium>;
val moltenIron = <fluid:iron>;
val moltenIronAlloy = <fluid:construction_alloy>;
val moltenLead = <fluid:lead>;
val moltenLumium = <fluid:lumium>;
val moltenManasteel = <fluid:manasteel>;
val moltenManyullyn = <fluid:manyullyn>;
val moltenMirion = <fluid:mirion>;
val moltenNickel = <fluid:nickel>;
val moltenPlatinum = <fluid:platinum>;
val moltenPsimetal = <fluid:psimetal>;
val moltenPulsatingIron = <fluid:pulsating_iron>;
val moltenRedstoneAlloy = <fluid:redstone_alloy>;
val moltenSignalum = <fluid:signalum>;
val moltenSilver = <fluid:silver>;
val moltenSoularium = <fluid:soularium>;
val moltenSteel = <fluid:steel>;
val moltenTerrasteel = <fluid:terrasteel>;
val moltenThaumium = <fluid:thaumium>;
val moltenTin = <fluid:tin>;
val moltenUranium = <fluid:uranium>;
val moltenVibrantAlloy = <fluid:vibrant_alloy>;

val copperOre = <embers:ore_copper>;
val leadOre = <embers:ore_lead>;
val silverOre = <embers:ore_silver>;
val quartzOre = <embers:ore_quartz>;

val copperIngot = <embers:ingot_copper>;
val leadIngot = <embers:ingot_lead>;
val silverIngot = <embers:ingot_silver>;

val copperPlate = <embers:plate_copper>;
val leadPlate = <embers:plate_lead>;
val silverPlate = <embers:plate_silver>;
val ironPlate = <embers:plate_iron>;
val goldPlate = <embers:plate_gold>;

val barStamp = <embers:stamp_bar>;
val plateStamp = <embers:stamp_plate>;
val gearStamp = <embers:stamp_gear>;

Grinder.removeRecipe(copperOre);
Grinder.removeRecipe(leadOre);
Grinder.removeRecipe(silverOre);
Grinder.removeRecipe(quartzOre);

furnace.remove(copperIngot, copperOre);
furnace.remove(leadIngot, leadOre);
furnace.remove(silverIngot, silverOre);

anyCopperOre.remove(copperOre);
anyLeadOre.remove(leadOre);
anySilverOre.remove(silverOre);
anyQuartzOre.remove(quartzOre);

val copperNugget = <embers:nugget_copper>;
val leadNugget = <embers:nugget_lead>;
val silverNugget = <embers:nugget_silver>;

val tinkersHammer = <embers:tinker_hammer>;

recipes.remove(copperIngot);
recipes.remove(leadIngot);
recipes.remove(silverIngot);

Stamper.remove(copperIngot);
Stamper.remove(leadIngot);
Stamper.remove(silverIngot);

Stamper.add(copperIngotTE, moltenCopper * 144, barStamp);
Stamper.add(leadIngotTE, moltenLead * 144, barStamp);
Stamper.add(silverIngotTE, moltenSilver * 144, barStamp);

Stamper.remove(ironPlate);
Stamper.remove(goldPlate);
Stamper.remove(copperPlate);
Stamper.remove(leadPlate);
Stamper.remove(silverPlate);

Stamper.add(ironPlateTE, moltenIron * 144, plateStamp);
Stamper.add(goldPlateTE, moltenGold * 144, plateStamp);
Stamper.add(copperPlateTE, moltenCopper * 144, plateStamp);
Stamper.add(leadPlateTE, moltenLead * 144, plateStamp);
Stamper.add(silverPlateTE, moltenSilver * 144, plateStamp);

anyIronPlate.remove(ironPlate);
anyGoldPlate.remove(goldPlate);
anyCopperPlate.remove(copperPlate);
anyLeadPlate.remove(leadPlate);
anySilverPlate.remove(silverPlate);

recipes.remove(copperNugget);
recipes.remove(leadNugget);
recipes.remove(silverNugget);

anyCopperIngot.remove(copperIngot);
anyLeadIngot.remove(leadIngot);
anySilverIngot.remove(silverIngot);

// Cannot remove these: they are generated by the Crystal Seeds and I don't know how to change it
//<ore:nuggetCopper>.remove(copperNugget);
//<ore:nuggetLead>.remove(leadNugget);
//<ore:nuggetSilver>.remove(silverNugget);

Mixer.add(moltenConstantan * 2, [moltenCopper * 1, moltenNickel * 1]);
Mixer.add(moltenBronze * 4, [moltenCopper * 3, moltenTin * 1]);
Mixer.add(moltenElectrum * 2, [moltenGold * 1, moltenSilver * 1]);
Mixer.add(moltenAluminumBrass * 4, [moltenAluminum * 3, moltenCopper * 1]);
Mixer.add(moltenManyullyn * 1, [moltenArdite * 1, moltenCobalt * 1]);

Melter.add(moltenAluminum * 288, anyAluminumOre);
Melter.add(moltenAluminum * 144, anyAluminumIngot);
Melter.add(moltenAluminum * 16, anyAluminumNugget);
Melter.add(moltenAluminum * 144, anyAluminumPlate);
Melter.add(moltenAluminum * 576, anyAluminumGear);
Melter.add(moltenAluminumBrass * 144, anyAluminumBrassIngot);
Melter.add(moltenAluminumBrass * 16, anyAluminumBrassNugget);
Melter.add(moltenAlumite * 144, anyAlumiteIngot);
Melter.add(moltenAlumite * 16, anyAlumiteNugget);
Melter.add(moltenBrass * 144, anyBrassIngot);
Melter.add(moltenBrass * 16, anyBrassNugget);
Melter.add(moltenBrass * 144, anyBrassPlate);
Melter.add(moltenBronze * 144, anyBronzeIngot);
Melter.add(moltenBronze * 16, anyBronzeNugget);
Melter.add(moltenBronze * 144, anyBronzePlate);
Melter.add(moltenBronze * 576, anyBronzeGear);
Melter.add(moltenConductiveIron * 144, anyConductiveIronIngot);
Melter.add(moltenConductiveIron * 16, anyConductiveIronNugget);
Melter.add(moltenConstantan * 144, anyConstantanIngot);
Melter.add(moltenConstantan * 16, anyConstantanNugget);
Melter.add(moltenConstantan * 144, anyConstantanPlate);
Melter.add(moltenConstantan * 576, anyConstantanGear);
Melter.add(moltenCopper * 576, anyCopperGear);
Melter.add(moltenDarkSteel * 144, anyDarkSteelIngot);
Melter.add(moltenDarkSteel * 16, anyDarkSteelNugget);
Melter.add(moltenElectricalSteel * 144, anyElectricalSteelIngot);
Melter.add(moltenElectricalSteel * 16, anyElectricalSteelNugget);
Melter.add(moltenElectrum * 144, anyElectrumIngot);
Melter.add(moltenElectrum * 16, anyElectrumNugget);
Melter.add(moltenElectrum * 144, anyElectrumPlate);
Melter.add(moltenElectrum * 576, anyElectrumGear);
Melter.add(moltenElementium * 144, anyElementiumIngot);
Melter.add(moltenElementium * 16, anyElementiumNugget);
Melter.add(moltenEndSteel * 144, anyEndSteelIngot);
Melter.add(moltenEndSteel * 16, anyEndSteelNugget);
Melter.add(moltenEnderium * 144, anyEnderiumIngot);
Melter.add(moltenEnderium * 16, anyEnderiumNugget);
Melter.add(moltenEnderium * 144, anyEnderiumPlate);
Melter.add(moltenEnderium * 576, anyEnderiumGear);
Melter.add(moltenEnergeticAlloy * 144, anyEnergeticAlloyIngot);
Melter.add(moltenEnergeticAlloy * 16, anyEnergeticAlloyNugget);
Melter.add(moltenGold * 576, anyGoldGear);
Melter.add(moltenInvar * 144, anyInvarIngot);
Melter.add(moltenInvar * 16, anyInvarNugget);
Melter.add(moltenInvar * 144, anyInvarPlate);
Melter.add(moltenInvar * 576, anyInvarGear);
Melter.add(moltenIridium * 144, anyIridiumPlate);
Melter.add(moltenIridium * 576, anyIridiumGear);
Melter.add(moltenIron * 576, anyIronGear);
Melter.add(moltenIronAlloy * 144, anyIronAlloyIngot);
Melter.add(moltenIronAlloy * 16, anyIronAlloyNugget);
Melter.add(moltenLead * 576, anyLeadGear);
Melter.add(moltenLumium * 144, anyLumiumIngot);
Melter.add(moltenLumium * 16, anyLumiumIngot);
Melter.add(moltenLumium * 144, anyLumiumPlate);
Melter.add(moltenLumium * 576, anyLumiumGear);
Melter.add(moltenManasteel * 144, anyManasteelIngot);
Melter.add(moltenManasteel * 16, anyManasteelNugget);
Melter.add(moltenManyullyn * 144, anyManyullynIngot);
Melter.add(moltenManyullyn * 16, anyManyullynNugget);
Melter.add(moltenMirion * 144, anyMirionIngot);
Melter.add(moltenMirion * 16, anyMirionNugget);
Melter.add(moltenNickel * 288, anyNickelOre);
Melter.add(moltenNickel * 144, anyNickelIngot);
Melter.add(moltenNickel * 16, anyNickelNugget);
Melter.add(moltenNickel * 144, anyNickelPlate);
Melter.add(moltenNickel * 576, anyNickelGear);
Melter.add(moltenPlatinum * 144, anyPlatinumPlate);
Melter.add(moltenPlatinum * 576, anyPlatinumGear);
Melter.add(moltenPsimetal * 144, anyPsimetalIngot);
Melter.add(moltenPulsatingIron * 144, anyPulsatingIronIngot);
Melter.add(moltenPulsatingIron * 16, anyPulsatingIronNugget);
Melter.add(moltenRedstoneAlloy * 144, anyRedstoneAlloyIngot);
Melter.add(moltenRedstoneAlloy * 16, anyRedstoneAlloyNugget);
Melter.add(moltenSignalum * 144, anySignalumIngot);
Melter.add(moltenSignalum * 16, anySignalumNugget);
Melter.add(moltenSignalum * 144, anySignalumPlate);
Melter.add(moltenSignalum * 576, anySignalumGear);
Melter.add(moltenSilver * 576, anySilverGear);
Melter.add(moltenSoularium * 144, anySoulariumIngot);
Melter.add(moltenSoularium * 16, anySoulariumNugget);
Melter.add(moltenSteel * 144, anySteelIngot);
Melter.add(moltenSteel * 16, anySteelNugget);
Melter.add(moltenSteel * 144, anySteelPlate);
Melter.add(moltenSteel * 576, anySteelGear);
Melter.add(moltenTerrasteel * 144, anyTerrasteelIngot);
Melter.add(moltenTerrasteel * 16, anyTerrasteelNugget);
Melter.add(moltenThaumium * 144, anyThaumiumIngot);
Melter.add(moltenThaumium * 16, anyThaumiumNugget);
Melter.add(moltenTin * 288, anyTinOre);
Melter.add(moltenTin * 144, anyTinIngot);
Melter.add(moltenTin * 16, anyTinNugget);
Melter.add(moltenTin * 144, anyTinPlate);
Melter.add(moltenTin * 576, anyTinGear);
Melter.add(moltenUranium * 144, anyUraniumPlate);
Melter.add(moltenVibrantAlloy * 144, anyVibrantAlloyIngot);
Melter.add(moltenVibrantAlloy * 16, anyVibrantAlloyNugget);

Stamper.add(aluminumIngotTE, moltenAluminum * 144, barStamp);
Stamper.add(aluminumPlate, moltenAluminum * 144, plateStamp);
Stamper.add(aluminumGear, moltenAluminum * 576, gearStamp);
Stamper.add(aluminumBrassIngot, moltenAluminumBrass * 144, barStamp);
Stamper.add(alumiteIngot, moltenAlumite * 144, barStamp);
Stamper.add(alchemicalBrassIngot, moltenBrass * 144, barStamp);
Stamper.add(brassPlate, moltenBrass * 144, plateStamp);
Stamper.add(bronzeIngot, moltenBronze * 144, barStamp);
Stamper.add(bronzePlate, moltenBronze * 144, plateStamp);
Stamper.add(bronzeGear, moltenBronze * 576, gearStamp);
Stamper.add(cobaltIngot, moltenCobalt * 144, barStamp);
Stamper.add(conductiveIronIngot, moltenConductiveIron * 144, barStamp);
Stamper.add(constantanIngot, moltenConstantan * 144, barStamp);
Stamper.add(constantanPlate, moltenConstantan * 144, plateStamp);
Stamper.add(constantanGear, moltenConstantan * 576, gearStamp);
Stamper.add(copperGear, moltenCopper * 576, gearStamp);
Stamper.add(darkSteelIngot, moltenDarkSteel * 144, barStamp);
Stamper.add(electricalSteelIngot, moltenElectricalSteel * 144, barStamp);
Stamper.add(electrumIngot, moltenElectrum * 144, barStamp);
Stamper.add(electrumPlate, moltenElectrum * 144, plateStamp);
Stamper.add(electrumGear, moltenElectrum * 576, gearStamp);
Stamper.add(endSteelIngot, moltenEndSteel * 144, barStamp);
Stamper.add(enderiumIngot, moltenEnderium * 144, barStamp);
Stamper.add(enderiumPlate, moltenEnderium * 144, plateStamp);
Stamper.add(enderiumGear, moltenEnderium * 576, gearStamp);
Stamper.add(energeticAlloyIngot, moltenEnergeticAlloy * 144, barStamp);
Stamper.add(goldGear, moltenGold * 576, gearStamp);
Stamper.add(invarIngot, moltenInvar * 144, barStamp);
Stamper.add(invarPlate, moltenInvar * 144, plateStamp);
Stamper.add(invarGear, moltenInvar * 576, gearStamp);
Stamper.add(iridiumPlate, moltenIridium * 144, plateStamp);
Stamper.add(iridiumGear, moltenIridium * 576, gearStamp);
Stamper.add(ironGear, moltenIron * 576, gearStamp);
Stamper.add(ironAlloyIngot, moltenIronAlloy * 144, barStamp);
Stamper.add(leadGear, moltenLead * 576, gearStamp);
Stamper.add(lumiumIngot, moltenLumium * 144, barStamp);
Stamper.add(lumiumPlate, moltenLumium * 144, plateStamp);
Stamper.add(lumiumGear, moltenLumium * 576, gearStamp);
Stamper.add(manasteelIngot, moltenManasteel * 144, barStamp);
Stamper.add(manyullynIngot, moltenManyullyn * 144, barStamp);
Stamper.add(mirionIngot, moltenMirion * 144, barStamp);
Stamper.add(nickelIngot, moltenNickel * 144, barStamp);
Stamper.add(nickelPlate, moltenNickel * 144, plateStamp);
Stamper.add(nickelGear, moltenNickel * 576, gearStamp);
Stamper.add(platinumGear, moltenPlatinum * 576, gearStamp);
Stamper.add(psimetalIngot, moltenPsimetal * 144, barStamp);
Stamper.add(pulsatingIronIngot, moltenPulsatingIron * 144, barStamp);
Stamper.add(redstoneAlloyIngot, moltenRedstoneAlloy * 144, barStamp);
Stamper.add(signalumIngot, moltenSignalum * 144, barStamp);
Stamper.add(signalumPlate, moltenSignalum * 144, plateStamp);
Stamper.add(signalumGear, moltenSignalum * 576, gearStamp);
Stamper.add(silverGear, moltenSilver * 576, gearStamp);
Stamper.add(soulariumIngot, moltenSoularium * 144, barStamp);
Stamper.add(steelIngot, moltenSteel * 144, barStamp);
Stamper.add(steelPlate, moltenSteel * 144, plateStamp);
Stamper.add(steelGear, moltenSteel * 576, gearStamp);
Stamper.add(terrasteelIngot, moltenTerrasteel * 144, barStamp);
Stamper.add(thaumiumIngot, moltenThaumium * 144, barStamp);
Stamper.add(thaumiumPlate, moltenThaumium * 144, plateStamp);
Stamper.add(tinIngot, moltenTin * 144, barStamp);
Stamper.add(tinPlate, moltenTin * 144, plateStamp);
Stamper.add(tinGear, moltenTin * 576, gearStamp);
Stamper.add(vibrantAlloyIngot, moltenVibrantAlloy * 144, barStamp);

